Public_Transit_Status="http://localhost:8888"
Kafka_URL=["PLAINTEXT://localhost:9092","PLAINTEXT://localhost:9093", "PLAINTEXT://localhost:9094"]
REST_Proxy_URL="http://localhost:8082/"
Schema_Registry_URL="http://localhost:8081/"
Kafka_Connect_URL="http://localhost:8083"
KSQL_URL="http://localhost:8088"
PostgreSQL_URL="jdbc:postgresql://localhost:5432/cta"
PostgreSQL_USERNAME="cta_admin"
PostgreSQL_PASSWORD="chicago"